name: Zip Release

on:
  release:
    types: [published]

jobs:
  zip-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: LICENSE.md shaders/
          dest: "Ebin-Resurrected-${{ github.event.release.tag_name }}.zip"
          recursive: false
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "Ebin-Resurrected-${{ github.event.release.tag_name }}.zip"
          asset_name: "Ebin-Resurrected-${{ github.event.release.tag_name }}.zip"
          tag: ${{ github.ref }}
  
